
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dougnjody
  namespace: dougnjody
  labels:
    app: dougnjody
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dougnjody
  template:
    metadata:
      labels:
        app: dougnjody
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dougnjody
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: dougnjody-nginx
        image: index.docker.io/hundredacrehome/dougnjody-nginx-arm7:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: hundredacrehome
---
apiVersion: v1
kind: Service
metadata:
  name: dougnjody-entrypoint
  namespace: dougnjody
spec:
  type: NodePort
  selector:
    app: dougnjody
  ports:
    - protocol: TCP
      name: http
      port: 80
      #targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dougnjody
  name: dougnjody-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.passHostHeader: "true"
    #traefik.backend.loadbalancer.sticky: "true"
spec:
  rules:
  - host: www.dougnjody.net
    http:
      paths:
      - path: /
        backend:
          serviceName: dougnjody-entrypoint
          servicePort: 80
